---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: project-mmp
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./projects/mmp/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client

