---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: msp-deploy
  namespace: msp
spec:
  interval: 1m0s
  path: ./flux
  prune: false
  serviceAccountName: msp
  targetNamespace: msp
  sourceRef:
    kind: GitRepository
    name: msp-deploy

