---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: msp-deploy
  namespace: msp
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/tnpugi/msp-deploy

