---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: mmp-deploy
  namespace: mmp
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/tnpugi/facebooc-deploy

