---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: mmp-deploy
  namespace: mmp
spec:
  interval: 1m0s
  path: ./flux
  prune: false
  serviceAccountName: mmp
  targetNamespace: mmp
  sourceRef:
    kind: GitRepository
    name: mmp-deploy

